language: node_js
sudo: false
services:
  - xvfb
matrix:
  include:
  - node_js: 14
  - node_js: 12
  fast_finish: true
env:
  global:
  - GIT_AUTHOR_EMAIL: APIs-GuruBot@users.noreply.github.com
  - GIT_AUTHOR_NAME: APIs-GuruBot
  - secure: RVRJijZYQ1MJnXi5iEUlmskCFnaYtM+DEAs8lffTpHVoHnArT6kQevQn0OY/BMjvTuviEvh6RFEB2SAIBUlTH7wHHhExk3q8h3w3AwPcU8AKvJFb4CcItz0MSYKNkua/fgbp2EzFC/kuB9JYdQP1MDfHSJc6JWhgYBuXSIj/H02/cBZDNPmtPIa0FNOlAD97LJraJ3yjtTJLO6c5u71VQPsO7P3KccTs4F5WzMC0kZwAPfXSLXju+o9TFj5wiLg1+6OwH0eZ4hDKSUS4+tkSTk0AqBXCYnUahlxBovIZBE/fKWqE8JQlL0tSuZxbrf0I01hoyFUVWdd3Uz4azT/VI0WQ9cUOotDOfHZ5NojYP9KSitlK/awmr3pqBVqacrq2n3h8BJo3CgVfKKzu1xUonBP3dkDLPgfjCztj0+IeJ3dTSpODADjrykVKujR0ZNk1e2l76UJc706gyAq/4EYPgPE0qhEVEyuTOMtGpK2FDL/InhD1XZSVlT93ZlBcfHwsBAtPLbWAygFHVOBygWTJJYKhf46CqddAxKi4aBmcDvxSihHY71vbB7OrJjHRxfEstOUJvTfQX8CDJmo0nIHu6gW9XL+9juauNW62bAkgTPyTBydxPTAKX4b4mVK9lnjER7V8ARx3UmVwDbw0v++fK+AOKul8FLlEhFED9wY4yaE=
  - secure: WxIg72wkIfv7pSwWqhBLRl18yxBW9tF441utXTdZ94vbDeQC/NokuxTGWOCEs2VVnbwDrnE1iQuwJJBYjqK8+mywSzcP5dnsxMVLLTkmV4aFOJUWDZrKxeWJ82NqwT8ZRCzXWdO8VPVxHE+ytf8O/CMgTfG3QmvoSTwuVno37Mv1I2eInnrqh9VPbsCgbzDto5q7BNee6XSsmITOMgsEcdnI8JeVpWRXiPWFb9U4nBm+em6rIZpdydCMH95RkWi3VsdcePxJ5pI44ksNgauR3ic6KLTxIL9GOW0KuPSk6+/BHz1xuq7Cetsl/UyZdHwDbp1XnAcOS8msYiL9HdVHbuGOLZx81V3Q3cy6fsrLOrDrCFkT+iJqUURfhaqsqc6lO9fbhcfLpCrfua6QaKJiGb5VQQHTXj8rXbHWQ7aQjW8VxGwAXfNrpDDqzSn3pESQjU5udkui3Z0QkSU8Cuvivc+6ttuqGgI2sXoXskwW03aHfAz9C3SIPZnTLEPTEKYyHzFDIDjeuZ622u2SWK+OF7nmCyRN5JGls/n6gqNYwfixMQTXXQujQXbZuZ2O9ytMMG1Aw8i+CuAvzPHU5JeO0PCWZjII4z9TsnVrBGJTmvziRtRU3bIOQeX9IDlg9UQmyfQJGAw45PhIr7hzSBKgM9qid5vYsz1mwRqRu34G4+4=
before_script:
- export DISPLAY=:99.0
script: gulp test
after_success:
- cat coverage/*/lcov.info > coveralls.txt
- cat coveralls.txt | node_modules/coveralls/bin/coveralls.js
cache:
  directories:
  - node_modules
